import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { pinoHttp } from 'pino-http';
import { logger } from './logger.js';
import { analyzeRouter } from './routes/analyze.js';
import { authRouter } from './routes/authRoutes.js';
import { complaintRouter } from './routes/complaintRoutes.js';

export function createApp() {
  const app = express();

  // 1. Security Headers (helmet)
  app.use(
    helmet({
      contentSecurityPolicy: false, // Allow client app assets during development
    })
  );

  // 2. CORS allowlist
  const allowedOrigins = process.env.ALLOWED_ORIGIN
    ? process.env.ALLOWED_ORIGIN.split(',').map((o) => o.trim())
    : ['http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:3000'];

  app.use(
    cors({
      origin: (origin, callback) => {
        // Allow requests with no origin (like mobile apps, curl, server-to-server)
        if (!origin || allowedOrigins.includes(origin) || process.env.NODE_ENV !== 'production') {
          callback(null, true);
        } else {
          callback(new Error('CORS policy: Not allowed by CORS'));
        }
      },
      credentials: true,
    })
  );

  // 3. Express Rate Limit
  const limiter = rateLimit({
    windowMs: 1 * 60 * 1000, // 1 minute
    max: 60, // Limit each IP to 60 requests per windowMs
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: 'Too many requests, please try again later.' },
  });
  app.use('/api/', limiter);

  // 4. Request Logging (redacting sensitive body/PII)
  app.use(
    pinoHttp({
      logger,
      serializers: {
        req: (req) => ({
          method: req.method,
          url: req.url,
        }),
      },
    })
  );

  // 5. JSON Body Parser (limit 1mb)
  app.use(express.json({ limit: '1mb' }));

  // 6. Routes
  app.get('/health', (_req, res) => {
    res.json({ status: 'ok', timestamp: Date.now() });
  });

  app.use('/api/analyze', analyzeRouter);
  app.use('/api/auth', authRouter);
  app.use('/api/complaints', complaintRouter);

  // Lightweight guardian alert endpoint for guest users (FR-14)
  app.post('/api/guardian-alert', (req, res) => {
    const { contact, summary, waLink } = req.body ?? {};
    logger.info({ contactPresent: Boolean(contact) }, 'Guardian alert generated by user.');
    return res.json({
      success: true,
      delivered: true,
      message: 'Guardian alert generated.',
      waLink,
    });
  });

  return app;
}
